### ISSUE TITLE
Timeout when using tuya-cli link

### ISSUE THREAD

**Issue by Nalwonk** [TuyaAPI/cli#111]
I am a complete newbie when it comes to working with this sort of thing, haven't used a command line regularly since the 90s, so I hope I'm not overlooking something incredibly obvious.

When I try to use the tuya-cli link command, I get the following, after it sits around for awhile trying to connect:
```
✖ Device(s) failed to be registered!
Error: Timed out waiting for devices to connect.
    at TuyaLinkWizard.linkDevice (/usr/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/index.js:117:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async link (/usr/lib/node_modules/@tuyapi/cli/lib/link.js:47:19)
```

I noticed someone else was having a similar problem with SSIDs with a space, but mine doesn't have one so I assume this is a different issue.  It DOES however use a capital letter, not sure if that's a problem or not.  I've noticed that I have the same problem even if I enter and incorrect SSID or password though, so it seems like even with the correct information entered, it's not getting past that stage.

Probably a dumb question, but the SSID and Password are for my normal home network, I entered it when I connected the last device I set up, so I'm assuming the SmartHome app is connecting to them through that.

I'm fairly sure the other information is entered correctly, because the Wizard was able to connect and get my device information

**Comment by codetheweb** [comment]
Just curious, why do you want to link your devices manually when the wizard works?

Make sure that the primary network connection of the computer you're running on is WiFi 2.4 GHz.

**Comment by Nalwonk** [comment]
Oh, did the wizard connect them?  I didn't quite understand what was going on well enough to know what the output from it was other than just telling me the information about the devices.

Sorry for the bother then, and thank you for the prompt reply.

**Comment by codetheweb** [comment]
Yeah, if the wizard spat out your IDs and keys that's all you need to connect to your devices. :)
