### ISSUE TITLE
  context: 'Timeout waiting for status response from device id:

### ISSUE THREAD

**Issue by cajonKA** [TuyaAPI/cli#118]
- I was able to link my device (LED color strip wifi) using cli and wizard.

-I am able to get all values with get and -a

-When trying to set a value, either DPS 1 true/false oder DPS5 and the color value, I always get the error:

 TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 192.168.xxx.xxx... +3ms
  TuyAPI Socket connected. +7ms
  TuyAPI GET Payload: +1ms
  TuyAPI {
  TuyAPI   gwId: '06200047bcddc2e641c1',
  TuyAPI   devId: '06200047bcddc2e641c1',
  TuyAPI   t: '1617400981',
  TuyAPI   dps: {},
  TuyAPI   uid: '06200047bcddc2e641c1'
  TuyAPI } +0ms
  TuyAPI SET Payload: +5ms
  TuyAPI {
  TuyAPI   devId: '06200047bcddc2e641c1',
  TuyAPI   gwId: '06200047bcddc2e641c1',
  TuyAPI   uid: '',
  TuyAPI   t: 1617400981,
  TuyAPI   dps: { '1': false }
  TuyAPI } +0ms
  TuyAPI Received data: 000055aa000000010000000a00000113000000007b226465764964223a223036323030303437626364646332653634316331222c22647073223a7b2231223a747275652c2232223a22636f6c6f7572222c2233223a3130302c2234223a302c2235223a223133303066663030663466666666222c2236223a226366333830303031363866666666222c2237223a226666666635303031303066663030222c2238223a226666666638303036666630303030303066663030303030306666666630303030666630303030666630303030222c2239223a226666666635303031666630303030222c223130223a226666666630353036666630303030303066663030666666663030666630306666303030306666666630303030227d7d9385d06a0000aa55 +7ms
  TuyAPI Parsed: +1ms
  TuyAPI {
  TuyAPI   payload: {
  TuyAPI     devId: '06200047bcddc2e641c1',
  TuyAPI     dps: {
  TuyAPI       '1': true,
  TuyAPI       '2': 'colour',
  TuyAPI       '3': 100,
  TuyAPI       '4': 0,
  TuyAPI       '5': '1300ff00f4ffff',
  TuyAPI       '6': 'cf38000168ffff',
  TuyAPI       '7': 'ffff500100ff00',
  TuyAPI       '8': 'ffff8006ff000000ff000000ffff0000ff0000ff0000',
  TuyAPI       '9': 'ffff5001ff0000',
  TuyAPI       '10': 'ffff0506ff000000ff00ffff00ff00ff0000ffff0000'
  TuyAPI     }
  TuyAPI   },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 1
  TuyAPI } +0ms
  TuyAPI Received DATA packet +1ms
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Timeout waiting for status response from device id: 06200047bcddc2e641c1')
    at TuyaDevice.emit (events.js:303:17)
    at /tmp/tuya/node_modules/tuyapi/index.js:344:12
    at Timeout._onTimeout (/tmp/tuya/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ERR_UNHANDLED_ERROR',
  context: 'Timeout waiting for status response from device id: 06200047bcddc2e641c1'
}
  TuyAPI Pinging 192.168.xxx.xxx +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +12ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 192.168.xxx.xxx +0ms
  TuyAPI Pinging 192.168.xxx.xxx +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +4ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 192.168.xxx.xxx +0ms

**Comment by codetheweb** [comment]
Have you tried using the v3.3 protocol (toggled with a flag)?

**Comment by cajonKA** [comment]
by appending --protocol-version 3.3 ?
I tried on the get command, version 3.1 returns correct value, 3.3 does 
not work and returns data format error
So I think I am still on a lower version

**Comment by codetheweb** [comment]
Is there anything else trying to control the device?

**Comment by cajonKA** [comment]
issue can be closed.
it seems that I still had some node red node trying to control it.
But I can no longer verify it because the debugging annoyed me so much that
I ended up flashing the controller using tuya convert.
and now it is running on Tasmota without issues.

Max Isom ***@***.***> schrieb am Mi., 7. Apr. 2021, 01:25:
