### ISSUE TITLE
AppleDouble error

### ISSUE THREAD

**Issue by gazzmanzx6** [TuyaAPI/cli#12]
Hi,

I am getting the following error in Raspbian Stretch when I run npm commands after installing TuyaAPI/cli.

npm ERR! code E404
npm ERR! 404 Not found : @tuyapi/.AppleDouble
npm ERR! 404
npm ERR! 404  '@tuyapi/.AppleDouble' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

The error goes if I remove TuyaApi/cli.

Any ideas what might be wrong?

Thanks.

**Comment by codetheweb** [comment]
That's a pretty strange error; what command are you running to install the CLI?

**Comment by gazzmanzx6** [comment]
I’m using npm i @tuyapi/cli -g

**Comment by codetheweb** [comment]
What happens if you make a new directory somewhere on your machine and try installing locally with `npm i @tuyapi/cli` (without the `-g` flag)?

**Comment by gazzmanzx6** [comment]
I tried installing locally but I can't get it run at all.I get command not found error.
I'm not in any way an expert with npm so have probably done something wrong.

**Comment by codetheweb** [comment]
Try prefixing with `npx` when using a local install.  For example: `npx tuya-cli --help`.
