### ISSUE TITLE
Ledvance - Timeout issue

### ISSUE THREAD

**Issue by FlagX** [TuyaAPI/cli#131]
Hi,
I have a [ledvance](https://play.google.com/store/apps/details?id=com.ldvsmartwifi.smart&hl=de_AT&gl=US) (GU10) light bulb, but I run into the familiar timeout issue. It seems to almost work, because once I use the `tuya-cli link` command the light bulb stops blinking (which usually indicates a successful registration), but it does not register in the tuya cloud.

Btw. I have monitored the ledvance app with android studio and it seems to communicate mostly with `a1.tuyaeu.com/api.json` (the content seems to be encrypted). Does anyone know if there is a usefull documentation/guide on how to use this api or is there any other way to retrieve the local key from this app?

**Comment by codetheweb** [comment]
There isn't any documentation on private HTTP APIs. The app may use a different API than TuyAPI, but that doesn't mean that TuyAPI won't work.

Are you able to tell if the device joins your network?

**Comment by FlagX** [comment]
Yes I can definitely see it connecting to my network.
![grafik](https://user-images.githubusercontent.com/9141923/128507628-af1065e9-63b3-497f-ae1c-505b1252c46d.png)

It stays connected, but if I turn it off and on again, it does not reconnect.

**Comment by codetheweb** [comment]
I would double-check the region parameter as that's the one thing that I can think of that would result it in connecting to the network but not authenticating correctly with Tuya.

Do you have other devices that you've successfully liked before? You may want to try the `tuya-cli wizard` method.

**Comment by FlagX** [comment]
Region should be correct (EU configured in tuya iot cloud, tuya link parameter is `--region eu`). The wizard does not work for me because i cannot get the ledvance bulbs registered in the tuya or smartlife app (only with the ldv wifi app).

I looked at the /v1.0/device/paring/tokens/{token} response via the API explorer (during the link procedure) which returns an `This device is not supported by this app` error:

![grafik](https://user-images.githubusercontent.com/9141923/128598323-4861fc91-1f63-4479-a05a-e5c4868d03db.png)

I think this is a `game over` for these ledvance bulbs?

**Comment by codetheweb** [comment]
> The wizard does not work for me because i cannot get the ledvance bulbs registered in the tuya or smartlife app (only with the ldv wifi app).

Sorry, if your device doesn't work with the official Tuya Smart app it won't work with TuyAPI. 

This has come up often enough that I'll add a note to `SETUP.md` about it.

**Comment by FlagX** [comment]
For anyone interested: I got the local key with a different method from here: https://community.home-assistant.io/t/ledvance-wifi-bulbs/301478/8
