### ISSUE TITLE
tuya-cli get --id xxxxxx keeps showing the -help content

### ISSUE THREAD

**Issue by ade-x1** [TuyaAPI/cli#139]
Hi everyone, I am trying to find more info on how to use my multi switch plug and I am interested on seeing what tuya-cli get should show. Unfortunately each time I try the command I only get the help. Any ideas of what's wrong?

tuya-cli get --id xxxxxx
Usage: tuya-cli get [options]

get a property on a device

Options:
  -s, --save                    save key so you can omit it for subsequent
                                commands
  --ip <ip_addr>                ip address of device
  --id <id>                     id of device
  --key [key]                   key of device
  --cid [cid_zigbee_device]     if specified, use device id of zigbee gateway
                                and cid of subdevice to get its status
  --dps [dps]                   property index to get
  --full                        get full response payload (default: false)
  --protocol-version [version]  tuya protocol version (default: 3.1)
  -h, --help                    display help for command

**Comment by codetheweb** [comment]
You're missing the `--key` parameter.
