### ISSUE TITLE
Add option to bind to specific IP

### ISSUE THREAD

**Issue by codetheweb** [TuyaAPI/cli#14]
Requested by @aleqx.

The AnyProxy module used currently doesn't have a relevent option, but there's an [open PR](https://github.com/alibaba/anyproxy/pull/459) that adds support.  I'll be able to add this feature once that gets merged and published.

**Comment by AMoo-Miki** [comment]
Would it be okay if I raised a PR to add IP binding to the new MITM solution?

**Comment by codetheweb** [comment]
Yeah, that'd be great.

**Comment by codetheweb** [comment]
Fixed by #28.
