### ISSUE TITLE
Tuya-cli not working

### ISSUE THREAD

**Issue by mhendu** [TuyaAPI/cli#140]
I am on Ubuntu 18.04 and successfully installed tuya-cli. Whenever I run it with whichever variables, I get a syntax error:

got.paginate = async function* (url, options) {

SyntaxError: Unexpected token *

**Comment by codetheweb** [comment]
You're probably on an old version of Node.js. Try installing v16.

**Comment by mhendu** [comment]
Got it, thanks. I was running from my Home Assistant PC which is a 32-bit
computer running Ubuntu 18.04. I was able to run the command via a virtual
machine on my desktop using Ubuntu 20.04.
