### ISSUE TITLE
Device registered and failed to be registered

### ISSUE THREAD

**Issue by Pieriot** [TuyaAPI/cli#142]
When running the 'tuya-cli link' command, I get both a 'registered' and 'failed to be registered' message.
"TypeError: link.getLinkedDevices is not a function"

![linkgetlinkeddevices](https://user-images.githubusercontent.com/8951671/147905488-d0b1e95b-af86-4641-8cad-6933f065638a.PNG)

The lights I'm trying to connect to stop flashing when the command is run so I assume it connects to a degree.

Sorry for the formatting and probably noob question, first time on github.

**Comment by codetheweb** [comment]
Whoops, I forgot to bump the minimum version for one of the dependencies.

Please upgrade to @tuyapi/cli v1.18.2 and try again.
