### ISSUE TITLE
 Waiting for request...

### ISSUE THREAD

**Issue by legolass73** [TuyaAPI/cli#18]
hello, 
today I tried to follow the "https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Setup-Instructions" tutorial
at one point it asks us to use tuya-cli list-app to recover "id" and "key" to add in homebridge, at the time of installation tuya-cli and AnyProxy I had warning messages for trucks called "deprecated" but tuya-cliu and anyproxy it is all the same installed. 
I started tuya-cli with port 3128 because I noticed that port 8001 was busy at home (app synology dsm)
I updated my page in the "tuya smart" app but nothing is displayed in the console... except the "Waiting for request..." which flickers but no other information that appears
can you help me?

Translated with www.DeepL.com/Translator

**Comment by legolass73** [comment]
npm WARN deprecated clipboard-js@0.3.6: Please migrate to https://github.com/lgarron/clipboard-polyfill 

npm WARN svg-inline-react@1.0.3 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must
 install peer dependencies yourself.

**Comment by codetheweb** [comment]
The error lies with one of the dependencies, rather than the tool itself.

I've found that sometimes I need to force-quit the app in the background and reopen it before it successfully gets captured.

**Comment by legolass73** [comment]
all right
