### ISSUE TITLE
Anyproxy no longer working with current iOS Tuya App

### ISSUE THREAD

**Issue by Apollon77** [TuyaAPI/cli#19]
@codetheweb 
I got reports on my side tht the proxy is no longer working with the most uptodate Handy apps. I also can reproduce that with the most current iOS App (3.10.1) :-(

Can you reproduce that or is it still working for you?

Charles Proxy is still working ...

**Comment by Apollon77** [comment]
When checking Charles then all requests are done using HTTP/2 and compressed ... compression should be supported by Anyproxy ... But all requests are shown as HTTP/1.1 there ... do'nt know if this is the problem ...

**Comment by Apollon77** [comment]
Info: it seems that on Android App version 3.9 is working, app 3.10 not ... Android older version could be available at https://github.com/Apollon77/ioBroker.tuya/issues/url

**Comment by Apollon77** [comment]
Is someone able to dig into the APp to check the differences? I would expect they added client certificated or other cert chain checking to the App ... but then decompiling could help to get the details /certs :)

**Comment by Apollon77** [comment]
One info from one user (unverified):

The main difference beetween the packages version is the node. I downgraded the debian's 10.15.2 to 8.16.0 from nodesource and the proxy start working, even with the 3.11 Smart Life app. Before that, i got the network error in the app.

**Comment by codetheweb** [comment]
Just tried with v8.16.0 and no success, although I do have the iOS 13 beta which may be part of the issue.

**Comment by Kleinstein-github** [comment]
tipp: make the iobroker hom plugin like the hombridge google home assistant plugin

**Comment by Apollon77** [comment]
What do you mean?

**Comment by Kleinstein-github** [comment]
i mean like this: https://github.com/basdelfos/homebridge-tuya-web with the google api

**Comment by Apollon77** [comment]
This is rather limited compared to the solution we have. And in fact the Proxy solution is still somehow working. Please use iobroker forum to get support.

**Comment by codetheweb** [comment]
Meant to update this but forgot.

I took another look a few days ago and since AnyProxy isn't working with any HTTPS sites, my guess is that the issue is on their side.

I contacted Tuya and asked them if it was possible to add the localKey to responses in the Home Assistant API, but they refused.

**Comment by Apollon77** [comment]
Maybe then we should open an issues anyproxy side??

**Comment by codetheweb** [comment]
There's already 176 open issues, many of them similar to the problem we're facing.  I think we need to find something else to use.

AnyProxy does work for HTTPS sites when requests come from my laptop, it just doesn't seem to work with iOS for some reason.

**Comment by Apollon77** [comment]
:-( I searched. very long time till I found Anyproxy to use it here :-(

**Comment by codetheweb** [comment]
https://github.com/codetheweb/tuyapi/issues/215#issuecomment-527269461

**Comment by Apollon77** [comment]
That sounds awesome! I will adjust my code, test by myself and and also let users test it. If that works we are back into the game ;-)

**Comment by Apollon77** [comment]
Adaopted your code and IT WORKS!! Great man. Thank you vry much!

**Comment by codetheweb** [comment]
No problem, glad to hear it.

**Comment by Apollon77** [comment]
@codetheweb I had some users with ECONNRESET and other ssl errors (https://github.com/Apollon77/ioBroker.tuya/issues/67) ... I did some changes inspired from e.g. https://github.com/joeferner/node-http-mitm-proxy/issues/165 and such ... see https://github.com/Apollon77/ioBroker.tuya/commit/83c4a50a939139831b8c2a8392f75cf8f07afa83 (main,js) ... I report back on results

**Comment by codetheweb** [comment]
👍

**Comment by Apollon77** [comment]
I also did some adjustments on my code like reading full message and not only one chunk. As soon as it is proven I Update here too

**Comment by Apollon77** [comment]
@codetheweb The lastest changes i did in my stuff to get it successfully working qith all problems cases from users is referenced in https://github.com/codetheweb/tuyapi/issues/250#issuecomment-531639344 ... If you are faster then me to get the changes from there I can also prepare a PR
