### ISSUE TITLE
request for --dps on get

### ISSUE THREAD

**Issue by greglarious** [TuyaAPI/cli#3]
it would be very helpful to be able to check the status of outlets other than 1

**Comment by codetheweb** [comment]
Good point, I thought I had added that, but I guess not.

I'll try to implement this later today.

**Comment by codetheweb** [comment]
Fixed with baaf82c94f57b9ab79749487593f350a6ddfedf7.  Please update to v1.2.1 with `npm i @tuyapi/cli -g` and then you should be able to use a `--dps` option with `get`.
