### ISSUE TITLE
Too many devices?

### ISSUE THREAD

**Issue by egeek** [TuyaAPI/cli#41]
I just tried the `list-app` command, and was able to connect to the proxy with my phone. However I seem to have too many devices on my network, as the console only lists some of them, then ends with:

`  },
  {
    name: 'Kitchen 5',
    id: '<REMOVED>',
    key: '<REMOVED>'
  },
  ... 147 more items
]`

Is there a way to write out the remaining 147?

**Comment by codetheweb** [comment]
Well.  I never expected someone to have 147 devices 😛.

I just published an update (@1.10.0) that allows you to add a `--out devices.json` flag to export the list to a JSON file rather than printing it out.  Hope that helps.
