### ISSUE TITLE
list-app only listening on ipv6 port

### ISSUE THREAD

**Issue by seansco** [TuyaAPI/cli#44]
if I run tuya-cli list-app it only binds with ipv6
 netstat -plnt
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -                          
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:45789           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:5900            0.0.0.0:*               LISTEN      17854/vino-server   
tcp6       0      0 :::111                  :::*                    LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
tcp6       0      0 ::1:631                 :::*                    LISTEN      -                   
tcp6       0      0 :::8001                 :::*                    LISTEN      18006/node          
tcp6       0      0 :::8002                 :::*                    LISTEN      18006/node          
tcp6       0      0 :::36363                :::*                    LISTEN      -                   
tcp6       0      0 :::5900                 :::*                    LISTEN      17854/vino-server

**Comment by codetheweb** [comment]
There's an option to specify what IP it binds to:
```
Usage: list-app [options]

list devices from Tuya Smart app (recommended for new users)

Options:
  --ip <ip_addr>      IP address to bind the proxy and certificate server to
  -p, --port [port]   port to use for proxy (default: 8001)
  --cert-port [port]  port to use for certificate download (default: 8002)
  -q, --omitQR        don't show the QR code for certificate setup
  -o, --out [file]    export devices to a JSON file instead of printing them (default: "")
  -h, --help          output usage information
```
