### ISSUE TITLE
command Slow

### ISSUE THREAD

**Issue by thib5** [TuyaAPI/cli#6]
when I run the command : tuya-cli set --id xxxxxxx --key tuya --set false xxxxx it could take up to 10 second before the light turn off...

**Comment by codetheweb** [comment]
This is because it has to find the IP of your device.  A PR should soon be merged that allows you to pass in your IP like this: `--ip "192.168.100.5"`, which should result in the command running much more quickly.  I'll let you know when that feature is available.
