### ISSUE TITLE
Network Error in Smart Life App when trying to refresh devices with the proxy

### ISSUE THREAD

**Issue by StefanoGiu** [TuyaAPI/cli#70]
Network Error in Smart Life App when trying to refresh devices with the proxy

- Run tuya-cli list-app
- Download the certificate and set up proxy on the android device
- Open Smart Life App and refresh the device
- I get Network Error
- I tried to use both last version of Smart Life and version 3.4.1

**Comment by codetheweb** [comment]
The proxy [no longer works](https://github.com/codetheweb/tuyapi/issues/280). Please check the [setup guide](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md) for instructions. (Note: Tuya has once again changed a few things around on their cloud platform and I haven't been able to update the docs yet. If you can't figure it out, wait a few days and check the instructions again.)
