### ISSUE TITLE
tuya-cli link error

### ISSUE THREAD

**Issue by lemassykoi** [TuyaAPI/cli#71]
Hi,

`pi@DomoticZ:~ 03:04 $ DEBUG=* tuya-cli link --api-key xxx --api-secret xxx --schema xxx --ssid xxx --password xxx --region eu

⠼ Registering devices(s)...  @tuyapi/link:wizard Token:  { region: 'EU', secret: 'BiTa', token: 'j1TssaEQ' } +0ms
  @tuyapi/link:manual Sending SmartLink initialization packets +0ms
  @tuyapi/link:wizard Polling cloud for details on token... +17ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +289ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +202ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +183ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +253ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +194ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +200ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +191ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +183ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +253ms
⠏ Registering devices(s)...  @tuyapi/link:manual Sending SmartLink data packets +2s
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +206ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +198ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +185ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +183ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +190ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +268ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +197ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +250ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +186ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +267ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +245ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +194ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +258ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +206ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +280ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +194ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +265ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +199ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +207ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +252ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +245ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +186ms
⠇ Registering devices(s)...  @tuyapi/link:manual Finished sending packets. +5s
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +248ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +180ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +247ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +187ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +251ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +252ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +189ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +259ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +270ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +190ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +196ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +189ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +246ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +244ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +245ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +253ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +264ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +191ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +193ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +207ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +275ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +195ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +287ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +216ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +266ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +269ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +275ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +194ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +194ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +212ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +211ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +246ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +182ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +260ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +190ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +265ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +265ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +202ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +193ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +266ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +198ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +240ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +245ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +182ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +268ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +260ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +192ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +198ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +207ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +253ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +189ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +249ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +248ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +178ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +181ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +242ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +265ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +188ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +266ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +189ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +191ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +267ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +264ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +258ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +263ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +189ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +192ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +190ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +260ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +178ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +241ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +247ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +197ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +190ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +257ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +259ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +197ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +262ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +265ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +276ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +268ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +189ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +276ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +265ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +279ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +184ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +183ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +243ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +261ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +202ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +266ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +194ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +268ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +189ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +246ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +180ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +193ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +277ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +245ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +178ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +186ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +185ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +196ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +269ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +202ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +241ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +182ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +259ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +186ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +241ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +243ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +269ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +190ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +262ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +195ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +259ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +255ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +246ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +241ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +255ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +190ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +188ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +180ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +183ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +181ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +265ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +261ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +259ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +265ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +181ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +243ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +184ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +189ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +263ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +269ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +197ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +262ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +259ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +264ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +257ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +185ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +181ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +187ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +250ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +178ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +242ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +239ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +257ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +258ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +270ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +196ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +258ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +267ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +187ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +258ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +259ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +193ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +195ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +259ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +265ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +190ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +259ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +188ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +195ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +257ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +187ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +266ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +265ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +257ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +255ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +264ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +188ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +189ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +262ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +187ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +192ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +260ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +192ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +186ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +256ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +266ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +189ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +260ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +261ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +275ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +245ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +180ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +188ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +189ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +188ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +178ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +181ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +178ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +259ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +197ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +225ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +189ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +253ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +252ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +258ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +188ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +189ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +266ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +257ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +261ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +275ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +260ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +190ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +187ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +268ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +259ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +190ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +262ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +189ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +265ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +188ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +262ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +241ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +180ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +181ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +263ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +185ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +259ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +264ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +187ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +186ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +242ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +247ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +248ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +189ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +200ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +224ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +193ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +830ms
✖ Device(s) failed to be registered!
Error: Timed out waiting for devices to connect.
    at TuyaLinkWizard.linkDevice (/usr/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/index.js:117:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async link (/usr/lib/node_modules/@tuyapi/cli/lib/link.js:47:19)`

The device is a Wifi outdoor Plug (2 plugs in one), worked well with smart life android app.

I created an account on IoT Tuya, process has changed a bit (Cloud API Authorization has been upgraded to SaaS Development Platform), but I have access ID and access Secret, so should it be ok ?

Thanks.
![image](https://user-images.githubusercontent.com/16377344/78620664-eb79da80-7880-11ea-9653-8582f4bea77c.png)

**Comment by codetheweb** [comment]
I recently updated the setup instructions, please take a look.  You might have missed the step of linking the app with the SaaS platform.

**Comment by lemassykoi** [comment]
I did it before writing issue, when I looked around. I hate complaining about things, so I try to avoid it as much as possible. Thanks.
![image](https://user-images.githubusercontent.com/16377344/78717815-7e6a5180-7921-11ea-974f-1920d37c2ec9.png)

**Comment by codetheweb** [comment]
I just tried creating a brand new SaaS application and app SDK, my device linked without an issue so your problem isn't related to the new platform structure.

Is the device you're running `tuya-cli link` on connected wirelessly to your network?

**Comment by lemassykoi** [comment]
Thanks, that was the answer I was waiting for, before trying another net device.
Actually, running tuya-cli on my raspberry pi, which is connected by network cable to my global switch. My wifi access point is connected too to this global switch.
Should I try with the Pi directly connected to wifi access point ? or should I connect the Pi to wifi too ?

Thanks again.

De : Max Isom <notifications@github.com>
Envoyé : jeudi 9 avril 2020 04:18
À : TuyaAPI/cli <cli@noreply.github.com>
Cc : Clément PAPPALARDO - I.P.C. <clement@ipc.tm>; Author <author@noreply.github.com>
Objet : Re: [TuyaAPI/cli] tuya-cli link error (#71)


I just tried creating a brand new SaaS application and app SDK, my device linked without an issue so your problem isn't related to the new platform structure.

Is the device you're running tuya-cli link on connected wirelessly to your network?

**Comment by codetheweb** [comment]
Yes, I'd try again with the Pi connected to your network via WiFi.

**Comment by lemassykoi** [comment]
I set up a new Pi, fresh, connected to wifi only, with just sudo apt install npm
when I start tuya-cli, few seconds after "manual Sending SmartLink data packets", my device stop led blinking, but still no answer (led blinking, then off for 2 seconds, then on for less than 1 second, then off)
tested with 2 new devices. Could the log be more verbose ? it seems that my device can react to the packets, maybe packets are too shorts ?

![image](https://user-images.githubusercontent.com/16377344/79004700-93c7c180-7b55-11ea-8287-d3db50823261.png)

![image](https://user-images.githubusercontent.com/16377344/79004685-8b6f8680-7b55-11ea-8a10-131d6df6931a.png)

Thanks

**Comment by lemassykoi** [comment]
edit : if I let my device plugged to AC (number 1 or number 2) after my try, after a moment, the device is connected to my local wifi, and have a valid dhcp address. However, still nothing on iot.tuya.com (0 devices)

**Comment by codetheweb** [comment]
If your device stops blinking, it usually means that it successfully connected to your network but had issues configuring itself with Tuya's cloud.  Is it possible there's anything between your device and Tuya's cloud services interfering with communication?

You could also try sniffing the traffic, but I'm not sure how much that'd help since it's all HTTPS and there's no way to install certificates on-device.

**Comment by lemassykoi** [comment]
I have a pfsense with snort.
are you trying to join iot.tuya.com during process ?

**Comment by lemassykoi** [comment]
![image](https://user-images.githubusercontent.com/16377344/79024159-66453d00-7b82-11ea-875a-36bf240fc538.png)

**Comment by lemassykoi** [comment]
here are packet capture from the device which is still powered on : 

![image](https://user-images.githubusercontent.com/16377344/79025429-f638b600-7b85-11ea-9dd9-ab83a02c59ed.png)

**Comment by lemassykoi** [comment]
Packet Capture during Link Process : 

![image](https://user-images.githubusercontent.com/16377344/79027532-d9ec4780-7b8c-11ea-8410-60458dd4d92e.png)

**Comment by lemassykoi** [comment]
ok, today, without any manipulation, I have 2 new devices in Tuya Linked Device

**Comment by codetheweb** [comment]
Hmm.  I don't know why it wasn't logged to the console, but I just added a new function to the CLI package that allows you to list all devices in your account.  Please update `@tuyapi/cli` to 1.12.0, then you should be able to do `tuya-cli cloud list --api-key your-key --api-secret your-secret --schema your-schema --region your-region`.

**Comment by lemassykoi** [comment]
Thanks for the update.

It returns nothing :

![image](https://user-images.githubusercontent.com/16377344/79078907-d92def80-7d0b-11ea-8d04-490e39c7a29b.png)

**Comment by codetheweb** [comment]
It should print something, even if it's just `[]`.  I just pushed an update that adds a `--version` flag (don't know why I didn't have that before); try upgrading again and do `tuya-cli --version` just to make sure it's up-to-date.

**Comment by lemassykoi** [comment]
Thanks, but infortunately, still nothing :

![image](https://user-images.githubusercontent.com/16377344/79252516-0d2b2100-7e82-11ea-9096-5f4c1b314b0f.png)

**Comment by lemassykoi** [comment]
Ok, you're right, my updates didn't get executed, despite message update is ok.

![image](https://user-images.githubusercontent.com/16377344/79252665-49f71800-7e82-11ea-8088-42562c043278.png)

**Comment by lemassykoi** [comment]
trying to install this : https://nodered.org/docs/getting-started/raspberrypi

![image](https://user-images.githubusercontent.com/16377344/79253361-5d56b300-7e83-11ea-803a-bc13c5142c1a.png)

if it's not ok, I will format Pi SD and start again from scratch.

**Comment by codetheweb** [comment]
I haven't used Node-RED before so I can't really help out there, sorry.

[This](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) might help.

**Comment by lemassykoi** [comment]
Thank you for the link. In this case, I only use Node Red installer because it's Pi-specific, and it's managing Node.js too. And as I'm not an expert in this, I thought it would be ok.
If I have to build from scratch, I will use as advised a Node Version manager.

**Comment by lemassykoi** [comment]
it's ok, my 2 devices are listed.

I successfully picked up values needed for use with Domoticz plugin : https://github.com/tixi/Domoticz-Tuya-SmartPlug-Plugin
And I can now control my devices within domoticz.

Thanks for your support. You can close.

**Comment by codetheweb** [comment]
Glad it's working.

Thank you [for the support](https://www.buymeacoffee.com/maxisom/c/182880) as well. 😄
