### ISSUE TITLE
Error: Error from socket device: <Device Name>?  But still functions?

### ISSUE THREAD

**Issue by Nodi-Rubrum** [TuyaAPI/cli#88]
This is weird, I have 4 smart plugs from the same vendor, Awow.  All for work without issue via my phone, all 4 work via the TUYA API, but one keeps reporting error from socket messages over and over, even though it actually works.  Any idea why this is the case?

**Comment by codetheweb** [comment]
Like @andrewmeepos [suggested](https://github.com/TuyaAPI/cli/issues/84#issuecomment-691883708), please try running your script in debug mode and post the output.

**Comment by Nodi-Rubrum** [comment]
Actually, I did figure it out.  As was discussed before, that there might be a conflicting connection.  I when around the environment, shutting down the various instances of NR, and other devices, and finally did find a device that was connecting to the specific smart plug that was disconnecting.  So mystery solved finally.   The idea that a double timeout really appears to be the case after all.

**Comment by codetheweb** [comment]
👍 glad you figured it out.
