### ISSUE TITLE
Wizard unable to fetch device

### ISSUE THREAD

**Issue by lishan89uc** [TuyaAPI/cli#98]
`There was an issue fetching that device. Make sure your account is linked and the ID is correct.`

I can't be sure but I think it has to do with the region. It might be because I made a China account before. Can anyone look into this?
Project page
![chrome_1MY2Zy5g7s](https://user-images.githubusercontent.com/24217695/99961777-da180c80-2d43-11eb-89ca-a987a0b29971.png)
Device List
![chrome_WZgvR2ClJm](https://user-images.githubusercontent.com/24217695/99961803-eac88280-2d43-11eb-8bed-cdc995c4fc5f.png)
Device List with America selected
![chrome_nuYtdnZNV6](https://user-images.githubusercontent.com/24217695/99961811-ed2adc80-2d43-11eb-8ff1-0f8159234830.png)

**Comment by codetheweb** [comment]
What region are you using with `tuya-cli wizard`?

**Comment by lishan89uc** [comment]
I am not sure if you can select region with `tuya-cli wizard`

**Comment by lishan89uc** [comment]
I found out what was happening i have to allow Authorization management, Device Management, Device Control.
![chrome_UXJjoCljgE](https://user-images.githubusercontent.com/24217695/100036814-c2796c00-2db5-11eb-9fdf-5bbc11ca0c8d.png)
